{
 "title": "Custom Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Exchange Rate from USD to EUR, JPY, and GBP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "currency_exchange_rate{target_currency=\"EUR\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "currency_exchange_rate{target_currency=\"JPY\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "currency_exchange_rate{target_currency=\"GBP\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Current Rates",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "currency_exchange_rate{base_currency=\"USD\"}",
     "legendFormat": "{{target_currency}}"
    }
   ]
  },
  {
   "title": "API Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "currency_api_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Time since last update",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - currency_data_timestamp_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Strongest Currency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "bottomk(1, currency_exchange_rate{base_currency=\"USD\"})",
     "legendFormat": "{{target_currency}}"
    }
   ]
  },
  {
   "title": "JPY to EUR rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "currency_exchange_rate{target_currency=\"JPY\"} / on(base_currency) currency_exchange_rate{target_currency=\"EUR\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "avg(currency_api_status)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "All Currencies",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "currency_exchange_rate", "legendFormat": "{{target_currency}}" }
   ]
  },
  {
   "title": "Average Exchange Rate Over 24 Hours",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(currency_exchange_rate[24h]))",
     "legendFormat": "{{target_currency}}"
    }
   ]
  },
  {
   "title": "Stats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "currency_exchange_rate", "legendFormat": "{{target_currency}}" }
   ]
  }
 ]
}